# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: forwintercms.bloghub::lang.model.comments.recordName

# Model Form Field configuration
form: $/forwintercms/bloghub/models/comment/fields.yaml

# Model Class name
modelClass: ForWinterCms\BlogHub\Models\Comment

# Default redirect location
defaultRedirect: forwintercms/bloghub/comments

# Create page
create:
    title: backend::lang.form.create_title
    redirect: forwintercms/bloghub/comments/update/:id
    redirectClose: forwintercms/bloghub/comments

# Update page
update:
    title: backend::lang.form.update_title
    redirect: forwintercms/bloghub/comments
    redirectClose: forwintercms/bloghub/comments

# Preview page
preview:
    title: backend::lang.form.preview_title
