# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: forwintercms.bloghub::lang.model.tags.recordName

# Model Form Field configuration
form: $/forwintercms/bloghub/models/tag/fields.yaml

# Model Class name
modelClass: ForWinterCms\BlogHub\Models\Tag

# Default redirect location
defaultRedirect: forwintercms/bloghub/tags

# Create page
create:
    title: backend::lang.form.create_title
    redirect: forwintercms/bloghub/tags/update/:id
    redirectClose: forwintercms/bloghub/tags

# Update page
update:
    title: backend::lang.form.update_title
    redirect: forwintercms/bloghub/tags
    redirectClose: forwintercms/bloghub/tags

# Preview page
preview:
    title: backend::lang.form.preview_title
