# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/forwintercms/bloghub/models/tag/columns.yaml

# Model Class name
modelClass: ForWinterCms\BlogHub\Models\Tag

# List Title
title: forwintercms.bloghub::lang.model.tags.manage

# Link URL for each record
recordUrl: forwintercms/bloghub/tags/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: slug
    direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
